### PR TITLE
Style fixes

### PR DESCRIPTION
**Pull request by ShyLee873**
Fixed the formatting of the jumbtron, nav bar now collapses when the viewport is at the min width, fixed media query issues.
image

### CODE REVIEW

**Comment by ShyLee873** [comment]
image

**Comment by jacobgwilliams** [comment]
@ShyLee873 It seems like some of @kostik700015 's authorization work is a part of your working branch for style fixes. When you created your feature branch, did you branch it off of master or off of `add_authorization` or one of the other auth branches? https://github.com/ShyLee873/rails-final/branches

**Comment by jacobgwilliams** [comment]
(but also nice nav burger 🍔)

**Comment by ShyLee873** [comment]
It was, I’m unfamiliar with how to work with actual people on GitHub 😅 So I pulled his changes and worked off that so I wouldn’t muck up any of the authentication stuff. Please advise? 😅

**Comment by jacobgwilliams** [comment]
@ShyLee873 Since Konstantin's last pull request with his auth changes [were merged](https://github.com/ShyLee873/rails-final/pull/15), then the master branch should be up to date with all these changes and you shouldn't have to worry about making sure they persist in your branch.

After Konstantin's branch was merged into the remote master branch, it's a good idea to checkout `master` locally and do a `git pull` to ensure that your local master contains all those changes. Then if you check out a feature branch from master, all those changes are already there.

In the event that two teammates are working on features simultaneously (as you all inevitably will be) then a way to avoid merge conflicts is as follows:

Say Engineer 1 and Engineer 2 checkout feature branches from master at the same time and work on them separately. Engineer 1 finishes their work, pushes it up, makes a pull request, and it gets approved and merged. **Now Engineer 2's master branch is behind**.

Once Engineer 2's branch work is done and they are ready to push it up and make a pull request, what they can do to avoid merge conflicts is:
- Make sure their changes are committed in their feature branch.
- Checkout `master`
- `Git fetch` and `git pull` to get local master up to date
- Checkout the feature branch again.
- Run `git merge master` - be aware that this merges `master` to whatever branch you're on, in this case, the feature branch. This is good because it gets your feature branch up to speed with master and this helps account for any discrepancies that might be important.
- ^ This may cause merge conflicts in the local feature branch. If it does, then they need to be resolved them (the text editor will show a "diff" between Engineer 2's local changes and the conflicting changes that couldn't be merged in automatically). Once everything is good to go, Eng 2 commits their feature branch to save the merge conflict resolution. They can then push it up and make a pull request.

**Comment by jacobgwilliams** [comment]
@ShyLee873 For now though, I believe what you need to try get your feature branch based off of `master` and not konstantin's branch is `git rebase`. Try looking into some docs or tutorials on the subject (I'm admittedly not an expert.) 

This article seems like it might be a place to start: https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase

**Pull request closed without merging**
