### PR TITLE
Adding authentication

### PR DESCRIPTION
**Pull request by kostik700015**

### CODE REVIEW

**Comment by jacobgwilliams** [comment]
@kostik700015 Remember to request a review on this pull request from @ShyLee873 and @Xxyumi-hub! (The option is in the top right corner of the page.) This sends a notification to their email prompting them to review your changes, and they'll be able to approve, comment or request changes.

**Review by ShyLee873 — CHANGES_REQUESTED** [review]
Everything looks good, however do you think it would be better to add the links for creating a new log in to the existing new user sign-up page? So the home page is the first thing the user sees (which can then be modified to reflect the home page's text and log in/forgot password fields)

**Comment by kostik700015** [comment]
> Everything looks good, however do you think it would be better to add the links for creating a new log in to the existing new user sign-up page? So the home page is the first thing the user sees (which can then be modified to reflect the home page's text and log in/forgot password fields)

Hi Shy! I am not sure I understand what you meant. We already have "sign in" link on "sign up" page, as well as "forgot password" and "sign up" links on "log in" page. Just in case I've added some screenshots. Would you like to create a mock up with your vision?

Untitled
Untitled2
Untitled3

**Comment by ShyLee873** [comment]
I was picturing the home page like this

Fitnest Home

And the new user sign up to look like this but the additional email/pw form fields inserted (with the 'about me' and the superfluous group field deleted)

Blank diagram

after which we can probably just create a new form to edit/update profiles to include the about me, update profile photo, etc.

**Comment by kostik700015** [comment]
OK I understand your idea, but it should be another ticket because it is related to visual design. I suggest to discuss it on Wednesday meeting.

**Review by ShyLee873 — APPROVED** [review]

**Review by Xxyumi-hub — APPROVED** [review]

**Pull request merged**
